pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'EnterpriseAnticheat'

include(
        'Anticheat',
        'API',
        'LegacyAPI',
        'ModernAPI',
        'Compat',
        'Compat-1_19_R3',
        'emulator'
)

project(':emulator').projectDir = file('Neo/neo')
